import React, { createContext, useContext, useState, useEffect } from 'react';

export type SupportedLanguage = 
  | 'en' // English
  | 'hi' // Hindi
  | 'bn' // Bengali
  | 'te' // Telugu
  | 'mr' // Marathi
  | 'ta' // Tamil
  | 'gu' // Gujarati
  | 'kn' // Kannada
  | 'ml' // Malayalam
  | 'pa' // Punjabi
  | 'or' // Odia
  | 'as'; // Assamese

export interface LanguageInfo {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    aiAssistant: 'AI Assistant',
    productCompliance: 'Product Compliance',
    standardsSearch: 'Standards Search',
    bisMarkVerification: 'BIS Mark Verification',
    complianceNavigator: 'Compliance Navigator',
    regulatoryUpdates: 'Regulatory Updates',
    laboratoryFinder: 'Laboratory Finder',
    documentsTemplates: 'Documents & Templates',
    complaintsSupport: 'Complaints & Support',
    adminDashboard: 'Admin Dashboard',
    savedWorkspace: 'Saved Workspace',
    productMatching: 'Product Matching',
    claimChecker: 'Product Claim Checker',
    bisOfficeLocator: 'BIS Office Locator',
    findApplicableStandard: 'Find Your Applicable Standard',
    describeProduct: 'Describe Product',
    searchByIsCode: 'Search by IS Code',
    uploadDocument: 'Upload Document',
    getStandards: 'Get Standards',
    verifyBisMark: 'Verify BIS Mark / Product',
    overallProgress: 'Overall Progress',
    recommendedForYou: 'Recommended for You',
    keyRequirements: 'Key Requirements (Summary)',
    recentActivity: 'Recent Activity',
    askSugamAi: 'Ask SUGAM-AI',
    viewStandard: 'View Standard',
    whyThisStandard: 'Why this Standard?',
    startComplianceJourney: 'Start Compliance Journey',
    viewAll: 'View All',
    searchPlaceholder: 'Ask about a product, standard, requirement or process...',
    demoDisclaimer: 'Demo data / estimates are for prototype demonstration only. Confirm current requirements with official BIS sources before making compliance decisions.',
    simplerCompliance: 'Simpler Compliance, Stronger India',
    standardsBuildTrust: 'Standards build trust, compliance builds a better tomorrow.',
    goodMorning: 'Good Morning',
    letsMakeComplianceSimpler: "Let's make compliance simpler, together.",
    activePlans: 'Active Plans',
    savedStandards: 'Saved Standards',
    verifications: 'Verifications',
    pendingDocuments: 'Pending Documents',
    requiredTests: 'Required Tests',
    documentsRequired: 'Documents Required',
    labsNearby: 'BIS Labs Nearby',
    applicableStandards: 'Applicable Standards',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    getStarted: 'Get Started',
    welcomeBack: 'Welcome Back'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    aiAssistant: 'एआई सहायक',
    productCompliance: 'उत्पाद अनुपालन',
    standardsSearch: 'मानक खोज',
    bisMarkVerification: 'बीआईएस मानक सत्यापन',
    complianceNavigator: 'अनुपालन नेविगेटर',
    regulatoryUpdates: 'नियामक अपडेट',
    laboratoryFinder: 'प्रयोगशाला खोजक',
    documentsTemplates: 'दस्तावेज़ और टेम्पलेट',
    complaintsSupport: 'शिकायतें और सहायता',
    adminDashboard: 'व्यवस्थापक डैशबोर्ड',
    savedWorkspace: 'सहेजा गया कार्यक्षेत्र',
    productMatching: 'उत्पाद मिलान',
    claimChecker: 'दावा सत्यापन',
    bisOfficeLocator: 'बीआईएस कार्यालय खोजक',
    findApplicableStandard: 'अपना लागू मानक खोजें',
    describeProduct: 'उत्पाद का विवरण दें',
    searchByIsCode: 'आईएस कोड द्वारा खोजें',
    uploadDocument: 'दस्तावेज़ अपलोड करें',
    getStandards: 'मानक प्राप्त करें',
    verifyBisMark: 'बीआईएस मार्क सत्यापित करें',
    overallProgress: 'कुल प्रगति',
    recommendedForYou: 'आपके लिए अनुशंसित',
    keyRequirements: 'प्रमुख आवश्यकताएं (सारांश)',
    recentActivity: 'हाल की गतिविधि',
    askSugamAi: 'सुगम-एआई से पूछें',
    viewStandard: 'मानक देखें',
    whyThisStandard: 'यह मानक क्यों?',
    startComplianceJourney: 'अनुपालन यात्रा शुरू करें',
    viewAll: 'सभी देखें',
    searchPlaceholder: 'उत्पाद, मानक, आवश्यकता या प्रक्रिया के बारे में पूछें...',
    demoDisclaimer: 'डेमो डेटा / अनुमान केवल प्रोटोटाइप प्रदर्शन के लिए हैं। अनुपालन निर्णय लेने से पहले आधिकारिक बीआईएस स्रोतों से पुष्टि करें।',
    simplerCompliance: 'सरल अनुपालन, सशक्त भारत',
    standardsBuildTrust: 'मानक विश्वास का निर्माण करते हैं, अनुपालन बेहतर कल बनाता है।',
    goodMorning: 'शुभ प्रभात',
    letsMakeComplianceSimpler: 'आइए मिलकर अनुपालन को आसान बनाएं।',
    activePlans: 'सक्रिय योजनाएं',
    savedStandards: 'सहेजे गए मानक',
    verifications: 'सत्यापन',
    pendingDocuments: 'लंबित दस्तावेज़',
    requiredTests: 'आवश्यक परीक्षण',
    documentsRequired: 'आवश्यक दस्तावेज़',
    labsNearby: 'निकटतम बीआईएस प्रयोगशालाएं',
    applicableStandards: 'लागू मानक',
    signIn: 'साइन इन करें',
    signOut: 'साइन आउट करें',
    getStarted: 'शुरू करें',
    welcomeBack: 'पुनः स्वागत है'
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    aiAssistant: 'এআই সহকারী',
    productCompliance: 'পণ্য সম্মতি',
    standardsSearch: 'মান সন্ধান',
    bisMarkVerification: 'বিআইএস মার্ক যাচাইকরণ',
    complianceNavigator: 'সম্মতি নেভিগেটর',
    regulatoryUpdates: 'নিয়ন্ত্রক আপডেট',
    laboratoryFinder: 'ল্যাবরেটরি অনুসন্ধান',
    documentsTemplates: 'নথিপত্র ও টেমপ্লেট',
    complaintsSupport: 'অভিযোগ ও সহায়তা',
    adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    savedWorkspace: 'সংরক্ষিত কর্মক্ষেত্র',
    productMatching: 'পণ্য ম্যাচিং',
    claimChecker: 'পণ্য দাবি যাচাইকারী',
    bisOfficeLocator: 'বিআইএস অফিস সন্ধানকারী',
    findApplicableStandard: 'প্রযোজ্য মান খুঁজুন',
    describeProduct: 'পণ্য বর্ণনা করুন',
    searchByIsCode: 'আইএস কোড দ্বারা সন্ধান',
    uploadDocument: 'নথি আপলোড করুন',
    getStandards: 'মান পান',
    verifyBisMark: 'বিআইএস মার্ক যাচাই করুন',
    overallProgress: 'সামগ্রিক অগ্রগতি',
    recommendedForYou: 'আপনার জন্য প্রস্তাবিত',
    keyRequirements: 'মূল প্রয়োজনীয়তা (সারাংশ)',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    askSugamAi: 'সুগম-এআই কে জিজ্ঞাসা করুন',
    viewStandard: 'মান দেখুন',
    whyThisStandard: 'কেন এই মান?',
    startComplianceJourney: 'সম্মতি যাত্রা শুরু করুন',
    viewAll: 'সব দেখুন',
    searchPlaceholder: 'পণ্য, মান, প্রয়োজনীয়তা বা প্রক্রিয়া সম্পর্কে জিজ্ঞাসা করুন...',
    demoDisclaimer: 'ডেমো ডেটা শুধুমাত্র প্রোটোটাইপ প্রদর্শনের জন্য।',
    simplerCompliance: 'সহজ সম্মতি, শক্তিশালী ভারত',
    standardsBuildTrust: 'মান বিশ্বাস গড়ে তোলে।',
    goodMorning: 'সুপ্রভাত',
    letsMakeComplianceSimpler: 'আসুন সম্মতি আরও সহজ করি।',
    activePlans: 'সক্রিয় পরিকল্পনা',
    savedStandards: 'সংরক্ষিত মান',
    verifications: 'যাচাইকরণ',
    pendingDocuments: 'মুলতুবি নথি',
    requiredTests: 'প্রয়োজনীয় পরীক্ষা',
    documentsRequired: 'প্রয়োজনীয় নথিপত্র',
    labsNearby: 'কাছের বিআইএস ল্যাব',
    applicableStandards: 'প্রযোজ্য মান',
    signIn: 'সাইন ইন',
    signOut: 'সাইন আউট',
    getStarted: 'শুরু করুন',
    welcomeBack: 'স্বাগতম'
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    aiAssistant: 'AI అసిస్టెంట్',
    productCompliance: 'ఉత్పత్తి సమ్మతి',
    standardsSearch: 'ప్రమాణాల శోధన',
    bisMarkVerification: 'BIS మార్క్ ధృవీకరణ',
    complianceNavigator: 'సమ్మతి నావిగేటర్',
    regulatoryUpdates: 'నియంత్రణ నవీకరణలు',
    laboratoryFinder: 'ప్రయోగశాల శోధకం',
    documentsTemplates: 'పత్రాలు & టెంప్లేట్లు',
    complaintsSupport: 'ఫిర్యాదులు & మద్దతు',
    adminDashboard: 'అడ్మిన్ డాష్‌బోర్డ్',
    savedWorkspace: 'సేవ్ చేసిన వర్క్‌స్పేస్',
    productMatching: 'ఉత్పత్తి సరిపోలిక',
    claimChecker: 'దావా తనిఖీ',
    bisOfficeLocator: 'BIS కార్యాలయ లొకేటర్',
    findApplicableStandard: 'వర్తించే ప్రమాణాన్ని కనుగొనండి',
    describeProduct: 'ఉత్పత్తిని వివరించండి',
    searchByIsCode: 'IS కోడ్ ద్వారా శోధించండి',
    uploadDocument: 'పత్రాన్ని అప్‌లోడ్ చేయండి',
    getStandards: 'ప్రమాణాలను పొందండి',
    verifyBisMark: 'BIS మార్క్‌ను ధృవీకరించండి',
    overallProgress: 'మొత్తం పురోగతి',
    recommendedForYou: 'మీ కోసం సిఫార్సు చేయబడింది',
    keyRequirements: 'కీలక అవసరాలు (సారాంశం)',
    recentActivity: 'ఇటీవలి కార్యాచరణ',
    askSugamAi: 'SUGAM-AI ని అడగండి',
    viewStandard: 'ప్రమాణాన్ని చూడండి',
    whyThisStandard: 'ఈ ప్రమాణం ఎందుకు?',
    startComplianceJourney: 'సమ్మతి ప్రయాణాన్ని ప్రారంభించండి',
    viewAll: 'అన్నీ చూడండి',
    searchPlaceholder: 'ఉత్పత్తి, ప్రమాణం, అవసరం లేదా ప్రక్రియ గురించి అడగండి...',
    demoDisclaimer: 'డెమో డేటా ప్రోటోటైప్ ప్రదర్శన కోసం మాత్రమే.',
    simplerCompliance: 'సరళమైన సమ్మతి, బలమైన భారతదేశం',
    standardsBuildTrust: 'ప్రమాణాలు నమ్మకాన్ని పెంచుతాయి.',
    goodMorning: 'శుభోదయం',
    letsMakeComplianceSimpler: 'సమ్మతిని మరింత సులభతరం చేద్దాం.',
    activePlans: 'క్రియాశీల ప్రణాళికలు',
    savedStandards: 'సేవ్ చేసిన ప్రమాణాలు',
    verifications: 'ధృవీకరణలు',
    pendingDocuments: 'పెండింగ్ పత్రాలు',
    requiredTests: 'అవసరమైన పరీక్షలు',
    documentsRequired: 'అవసరమైన పత్రాలు',
    labsNearby: 'సమీపంలోని BIS ల్యాబ్‌లు',
    applicableStandards: 'వర్తించే ప్రమాణాలు',
    signIn: 'సైన్ ఇన్',
    signOut: 'సైన్ అవుట్',
    getStarted: 'ప్రారంభించండి',
    welcomeBack: 'తిరిగి స్వాగతం'
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    aiAssistant: 'एआय सहाय्यक',
    productCompliance: 'उत्पादन अनुपालन',
    standardsSearch: 'मानके शोध',
    bisMarkVerification: 'बीआयएस मार्क पडताळणी',
    complianceNavigator: 'अनुपालन नेव्हिगेटर',
    regulatoryUpdates: 'नियामक अद्यतने',
    laboratoryFinder: 'प्रयोगशाळा शोधक',
    documentsTemplates: 'दस्तऐवज आणि टेम्पलेट्स',
    complaintsSupport: 'तक्रारी आणि मदत',
    adminDashboard: 'प्रशासक डॅशबोर्ड',
    savedWorkspace: 'जतन केलेले कार्यक्षेत्र',
    productMatching: 'उत्पादन जुळणी',
    claimChecker: 'उत्पादन दावा तपासक',
    bisOfficeLocator: 'बीआयएस कार्यालय शोधक',
    findApplicableStandard: 'लागू मानक शोधा',
    describeProduct: 'उत्पादनाचे वर्णन करा',
    searchByIsCode: 'आयएस कोड द्वारे शोधा',
    uploadDocument: 'दस्तऐवज अपलोड करा',
    getStandards: 'मानके मिळवा',
    verifyBisMark: 'बीआयएस मार्क तपासा',
    overallProgress: 'एकूण प्रगती',
    recommendedForYou: 'तुमच्यासाठी शिफारस केलेले',
    keyRequirements: 'प्रमुख आवश्यकता (थोडक्यात)',
    recentActivity: 'अलीकडील क्रियाकलाप',
    askSugamAi: 'सुगम-एआय ला विचारा',
    viewStandard: 'मानक पहा',
    whyThisStandard: 'हे मानक का?',
    startComplianceJourney: 'अनुपालन प्रवास सुरू करा',
    viewAll: 'सर्व पहा',
    searchPlaceholder: 'उत्पादन, मानक किंवा प्रक्रियेबद्दल विचारा...',
    demoDisclaimer: 'डेमो डेटा केवळ प्रात्यक्षिकासाठी आहे.',
    simplerCompliance: 'सोपे अनुपालन, सशक्त भारत',
    standardsBuildTrust: 'मानके विश्वास निर्माण करतात.',
    goodMorning: 'शुभ सकाळ',
    letsMakeComplianceSimpler: 'अनुपालन अधिक सोपे करूया.',
    activePlans: 'सक्रिय योजना',
    savedStandards: 'जतन केलेली मानके',
    verifications: 'पडताळणी',
    pendingDocuments: 'प्रलंबित कागदपत्रे',
    requiredTests: 'आवश्यक चाचण्या',
    documentsRequired: 'आवश्यक कागदपत्रे',
    labsNearby: 'जवळपासच्या बीआयएस लॅब',
    applicableStandards: 'लागू मानके',
    signIn: 'साइन इन',
    signOut: 'साइन आउट',
    getStarted: 'सुरू करा',
    welcomeBack: 'पुन्हा स्वागत आहे'
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    aiAssistant: 'AI உதவியாளர்',
    productCompliance: 'தயாரிப்பு இணக்கம்',
    standardsSearch: 'தரநிலைகள் தேடல்',
    bisMarkVerification: 'BIS குறியீடு சரிபார்ப்பு',
    complianceNavigator: 'இணக்க வழிகாட்டி',
    regulatoryUpdates: 'ஒழுங்குமுறை புதுப்பிப்புகள்',
    laboratoryFinder: 'ஆய்வகக் கண்டுபிடிப்பான்',
    documentsTemplates: 'ஆவணங்கள் & மாதிரிகள்',
    complaintsSupport: 'புகார்கள் & ஆதரவு',
    adminDashboard: 'நிர்வாக டாஷ்போர்டு',
    savedWorkspace: 'சேமிக்கப்பட்ட பணியிடம்',
    productMatching: 'தயாரிப்பு பொருத்தம்',
    claimChecker: 'கோரிக்கை சரிபார்ப்பான்',
    bisOfficeLocator: 'BIS அலுவலக இருப்பிடம்',
    findApplicableStandard: 'பொருந்தக்கூடிய தரநிலையைக் கண்டறியவும்',
    describeProduct: 'தயாரிப்பை விவரிக்கவும்',
    searchByIsCode: 'IS குறியீடு மூலம் தேடவும்',
    uploadDocument: 'ஆவணத்தை பதிவேற்றவும்',
    getStandards: 'தரநிலைகளைப் பெறுங்கள்',
    verifyBisMark: 'BIS குறியீட்டைச் சரிபார்க்கவும்',
    overallProgress: 'ஒட்டுமொத்த முன்னேற்றம்',
    recommendedForYou: 'உங்களுக்காக பரிந்துரைக்கப்பட்டது',
    keyRequirements: 'முக்கிய தேவைகள் (சுருக்கம்)',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    askSugamAi: 'SUGAM-AI யிடம் கேளுங்கள்',
    viewStandard: 'தரநிலையைக் காண்க',
    whyThisStandard: 'இந்தத் தரம் ஏன்?',
    startComplianceJourney: 'இணக்கப் பயணத்தைத் தொடங்குங்கள்',
    viewAll: 'அனைத்தையும் காண்க',
    searchPlaceholder: 'தயாரிப்பு அல்லது தரம் குறித்து கேளுங்கள்...',
    demoDisclaimer: 'டெமோ தரவு மாதிரி பயன்பாட்டிற்கு மட்டுமே.',
    simplerCompliance: 'எளிய இணக்கம், வலிமையான இந்தியா',
    standardsBuildTrust: 'தரநிலைகள் நம்பிக்கையை உருவாக்குகின்றன.',
    goodMorning: 'காலை வணக்கம்',
    letsMakeComplianceSimpler: 'இணக்கத்தை எளிமையாக்குவோம்.',
    activePlans: 'செயலில் உள்ள திட்டங்கள்',
    savedStandards: 'சேமித்த தரநிலைகள்',
    verifications: 'சரிபார்ப்புகள்',
    pendingDocuments: 'நிலுவையில் உள்ள ஆவணங்கள்',
    requiredTests: 'தேவையான சோதனைகள்',
    documentsRequired: 'தேவையான ஆவணங்கள்',
    labsNearby: 'அருகிலுள்ள BIS ஆய்வகங்கள்',
    applicableStandards: 'பொருந்தும் தரநிலைகள்',
    signIn: 'உள்நுழைக',
    signOut: 'வெளியேறுக',
    getStarted: 'தொடங்குங்கள்',
    welcomeBack: 'மீண்டும் வருக'
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    aiAssistant: 'AI સહાયક',
    productCompliance: 'ઉત્પાદન અનુપાલન',
    standardsSearch: 'ધોરણોની શોધ',
    bisMarkVerification: 'BIS માર્ક ચકાસણી',
    complianceNavigator: 'અનુપાલન નેવિગેટર',
    regulatoryUpdates: 'નિયમનકારી અપડેટ્સ',
    laboratoryFinder: 'લેબોરેટરી શોધક',
    documentsTemplates: 'દસ્તાવેજો અને નમૂનાઓ',
    complaintsSupport: 'ફરિયાદો અને સહાય',
    adminDashboard: 'એડમિન ડેશબોર્ડ',
    savedWorkspace: 'સાચવેલ કાર્યક્ષેત્ર',
    productMatching: 'ઉત્પાદન મેચિંગ',
    claimChecker: 'ઉત્પાદન દાવો ચકાસનાર',
    bisOfficeLocator: 'BIS કચેરી શોધક',
    findApplicableStandard: 'લાગુ પડતું ધોરણ શોધો',
    describeProduct: 'ઉત્પાદનનું વર્ણન કરો',
    searchByIsCode: 'IS કોડ દ્વારા શોધો',
    uploadDocument: 'દસ્તાવેજ અપલોડ કરો',
    getStandards: 'ધોરણો મેળવો',
    verifyBisMark: 'BIS માર્ક ચકાસો',
    overallProgress: 'સમગ્ર પ્રગતિ',
    recommendedForYou: 'તમારા માટે ભલામણ કરેલ',
    keyRequirements: 'મુખ્ય જરૂરિયાતો (સારાંશ)',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    askSugamAi: 'SUGAM-AI ને પૂછો',
    viewStandard: 'ધોરણ જુઓ',
    whyThisStandard: 'આ ધોરણ શા માટે?',
    startComplianceJourney: 'અનુપાલન યાત્રા શરૂ કરો',
    viewAll: 'બધું જુઓ',
    searchPlaceholder: 'ઉત્પાદન અથવા ધોરણ વિશે પૂછો...',
    demoDisclaimer: 'ડેમો ડેટા ફક્ત પ્રોટોટાઇપ પ્રદર્શન માટે છે.',
    simplerCompliance: 'સરળ અનુપાલન, સક્ષમ ભારત',
    standardsBuildTrust: 'ધોરણો વિશ્વાસનું નિર્માણ કરે છે.',
    goodMorning: 'સુપ્રભાત',
    letsMakeComplianceSimpler: 'ચાલો સાથે મળીને અનુપાલન સરળ બનાવીએ.',
    activePlans: 'સક્રિય યોજનાઓ',
    savedStandards: 'સાચવેલ ધોરણો',
    verifications: 'ચકાસણીઓ',
    pendingDocuments: 'બાકી દસ્તાવેજો',
    requiredTests: 'જરૂરી પરીક્ષણો',
    documentsRequired: 'જરૂરી દસ્તાવેજો',
    labsNearby: 'નજીકની BIS લેબ્સ',
    applicableStandards: 'લાગુ પડતા ધોરણો',
    signIn: 'સાઇન ઇન',
    signOut: 'સાઇન આઉટ',
    getStarted: 'શરૂ કરો',
    welcomeBack: 'પુનઃ સ્વાગત છે'
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    aiAssistant: 'AI ಸಹಾಯಕ',
    productCompliance: 'ಉತ್ಪನ್ನ ಅನುಸರಣೆ',
    standardsSearch: 'ಪ್ರಮಾಣಕಗಳ ಹುಡುಕಾಟ',
    bisMarkVerification: 'BIS ಮಾರ್ಕ್ ಪರಿಶೀಲನೆ',
    complianceNavigator: 'ಅನುಸರಣೆ ನ್ಯಾವಿಗೇಟರ್',
    regulatoryUpdates: 'ನಿಯಂತ್ರಕ ನವೀಕರಣಗಳು',
    laboratoryFinder: 'ಪ್ರಯೋಗಾಲಯ ಶೋಧಕ',
    documentsTemplates: 'ದಾಖಲೆಗಳು ಮತ್ತು ಮಾದರಿಗಳು',
    complaintsSupport: 'ದೂರುಗಳು ಮತ್ತು ಬೆಂಬಲ',
    adminDashboard: 'ನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    savedWorkspace: 'ಉಳಿಸಿದ ಕಾರ್ಯಕ್ಷೇತ್ರ',
    productMatching: 'ಉತ್ಪನ್ನ ಹೊಂದಾಣಿಕೆ',
    claimChecker: 'ಹಕ್ಕು ಪರಿಶೀಲಕ',
    bisOfficeLocator: 'BIS ಕಚೇರಿ ಶೋಧಕ',
    findApplicableStandard: 'ಅನ್ವಯವಾಗುವ ಪ್ರಮಾಣಕವನ್ನು ಹುಡುಕಿ',
    describeProduct: 'ಉತ್ಪನ್ನವನ್ನು ವಿವರಿಸಿ',
    searchByIsCode: 'IS ಕೋಡ್ ಮೂಲಕ ಹುಡುಕಿ',
    uploadDocument: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    getStandards: 'ಪ್ರಮಾಣಕಗಳನ್ನು ಪಡೆಯಿರಿ',
    verifyBisMark: 'BIS ಮಾರ್ಕ್ ಪರಿಶೀಲಿಸಿ',
    overallProgress: 'ಒಟ್ಟಾರೆ ಪ್ರಗತಿ',
    recommendedForYou: 'ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
    keyRequirements: 'ಪ್ರಮುಖ ಅಗತ್ಯತೆಗಳು (ಸಾರಾಂಶ)',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    askSugamAi: 'SUGAM-AI ಅನ್ನು ಕೇಳಿ',
    viewStandard: 'ಪ್ರಮಾಣಕ ವೀಕ್ಷಿಸಿ',
    whyThisStandard: 'ಈ ಪ್ರಮಾಣಕ ಏಕೆ?',
    startComplianceJourney: 'ಅನುಸರಣೆ ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    searchPlaceholder: 'ಉತ್ಪನ್ನ ಅಥವಾ ಪ್ರಮಾಣಕದ ಬಗ್ಗೆ ಕೇಳಿ...',
    demoDisclaimer: 'ಡೆಮೊ ಡೇಟಾ ಕೇವಲ ಪ್ರದರ್ಶನಕ್ಕಾಗಿ.',
    simplerCompliance: 'ಸರಳ ಅನುಸರಣೆ, ಬಲಿಷ್ಠ ಭಾರತ',
    standardsBuildTrust: 'ಪ್ರಮಾಣಕಗಳು ನಂಬಿಕೆಯನ್ನು ಬೆಳೆಸುತ್ತವೆ.',
    goodMorning: 'ಶುಭೋದಯ',
    letsMakeComplianceSimpler: 'ಅನುಸರಣೆಯನ್ನು ಸರಳಗೊಳಿಸೋಣ.',
    activePlans: 'ಸಕ್ರಿಯ ಯೋಜನೆಗಳು',
    savedStandards: 'ಉಳಿಸಿದ ಪ್ರಮಾಣಕಗಳು',
    verifications: 'ಪರಿಶೀಲನೆಗಳು',
    pendingDocuments: 'ಬಾಕಿ ಉಳಿದ ದಾಖಲೆಗಳು',
    requiredTests: 'ಅಗತ್ಯ ಪರೀಕ್ಷೆಗಳು',
    documentsRequired: 'ಅಗತ್ಯ ದಾಖಲೆಗಳು',
    labsNearby: 'ಹತ್ತಿರದ BIS ಲ್ಯಾಬ್‌ಗಳು',
    applicableStandards: 'ಅನ್ವಯವಾಗುವ ಪ್ರಮಾಣಕಗಳು',
    signIn: 'ಸೈನ್ ಇನ್',
    signOut: 'ಸೈನ್ ಔಟ್',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ'
  },
  ml: {
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    aiAssistant: 'AI അസിസ്റ്റന്റ്',
    productCompliance: 'ഉൽപ്പന്ന പാലനം',
    standardsSearch: 'നിലവാരങ്ങൾ തിരയുക',
    bisMarkVerification: 'BIS മാർക്ക് പരിശോധന',
    complianceNavigator: 'കംപ്ലയൻസ് നാവിഗേറ്റർ',
    regulatoryUpdates: 'റെഗുലേറ്ററി അപ്‌ഡേറ്റുകൾ',
    laboratoryFinder: 'ലബോറട്ടറി ഫൈൻഡർ',
    documentsTemplates: 'രേഖകളും ടെംപ്ലേറ്റുകളും',
    complaintsSupport: 'പരാതികളും പിന്തുണയും',
    adminDashboard: 'അഡ്മിൻ ഡാഷ്‌ബോർഡ്',
    savedWorkspace: 'സേവ് ചെയ്ത വർക്ക്‌സ്‌പേസ്',
    productMatching: 'ഉൽപ്പന്ന പൊരുത്തം',
    claimChecker: 'ഉൽപ്പന്ന അവകാശവാദ പരിശോധകൻ',
    bisOfficeLocator: 'BIS ഓഫീസ് ലൊക്കേറ്റർ',
    findApplicableStandard: 'ബാധകമായ മാനദണ്ഡം കണ്ടെത്തുക',
    describeProduct: 'ഉൽപ്പന്നം വിവരിക്കുക',
    searchByIsCode: 'IS കോഡ് ഉപയോഗിച്ച് തിരയുക',
    uploadDocument: 'രേഖ അപ്‌ലോഡ് ചെയ്യുക',
    getStandards: 'മാനദണ്ഡങ്ങൾ നേടുക',
    verifyBisMark: 'BIS മാർക്ക് പരിശോധിക്കുക',
    overallProgress: 'മൊത്തത്തിലുള്ള പുരോഗതി',
    recommendedForYou: 'നിങ്ങൾക്കായി ശുപാർശ ചെയ്യുന്നത്',
    keyRequirements: 'പ്രധാന ആവശ്യകതകൾ (സംഗ്രഹം)',
    recentActivity: 'സമീപകാല പ്രവർത്തനം',
    askSugamAi: 'SUGAM-AI യോട് ചോദിക്കുക',
    viewStandard: 'മാനദണ്ഡം കാണുക',
    whyThisStandard: 'എന്തുകൊണ്ട് ഈ മാനദണ്ഡം?',
    startComplianceJourney: 'കംപ്ലയൻസ് യാത്ര ആരംഭിക്കുക',
    viewAll: 'എല്ലാം കാണുക',
    searchPlaceholder: 'ഉൽപ്പന്നം അല്ലെങ്കിൽ മാനദണ്ഡത്തെക്കുറിച്ച് ചോദിക്കുക...',
    demoDisclaimer: 'ഡെമോ ഡാറ്റ പ്രോട്ടോടൈപ്പ് ആവശ്യങ്ങൾക്ക് മാത്രമുള്ളതാണ്.',
    simplerCompliance: 'ലളിതമായ പാലനം, ശക്തമായ ഭാരതം',
    standardsBuildTrust: 'നിലവാരങ്ങൾ വിശ്വാസം വളർത്തുന്നു.',
    goodMorning: 'സുപ്രഭാതം',
    letsMakeComplianceSimpler: 'പാലനം കൂടുതൽ ലളിതമാക്കാം.',
    activePlans: 'സജീവ പ്ലാനുകൾ',
    savedStandards: 'സേവ് ചെയ്ത നിലവാരങ്ങൾ',
    verifications: 'പരിശോധനകൾ',
    pendingDocuments: 'തീർപ്പുകൽപ്പിക്കാത്ത രേഖകൾ',
    requiredTests: 'ആവശ്യമായ പരിശോധനകൾ',
    documentsRequired: 'ആവശ്യമായ രേഖകൾ',
    labsNearby: 'അടുത്തുള്ള BIS ലാബുകൾ',
    applicableStandards: 'ബാധകമായ മാനദണ്ഡങ്ങൾ',
    signIn: 'സൈൻ ഇൻ',
    signOut: 'സൈൻ ഔട്ട്',
    getStarted: 'ആരംഭിക്കുക',
    welcomeBack: 'വീണ്ടും സ്വാഗതം'
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    aiAssistant: 'AI ਸਹਾਇਕ',
    productCompliance: 'ਉਤਪਾਦ ਪਾਲਣਾ',
    standardsSearch: 'ਮਿਆਰਾਂ ਦੀ ਖੋਜ',
    bisMarkVerification: 'BIS ਮਾਰਕ ਤਸਦੀਕ',
    complianceNavigator: 'ਪਾਲਣਾ ਨੈਵੀਗੇਟਰ',
    regulatoryUpdates: 'ਰੈਗੂਲੇਟਰੀ ਅੱਪਡੇਟ',
    laboratoryFinder: 'ਪ੍ਰਯੋਗਸ਼ਾਲਾ ਖੋਜਕ',
    documentsTemplates: 'ਦਸਤਾਵੇਜ਼ ਅਤੇ ਨਮੂਨੇ',
    complaintsSupport: 'ਸ਼ਿਕਾਇਤਾਂ ਅਤੇ ਸਹਾਇਤਾ',
    adminDashboard: 'ਐਡਮਿਨ ਡੈਸ਼ਬੋਰਡ',
    savedWorkspace: 'ਸੰਭਾਲਿਆ ਵਰਕਸਪੇਸ',
    productMatching: 'ਉਤਪਾਦ ਮੇਲ',
    claimChecker: 'ਦਾਅਵਾ ਜਾਂਚਕਰਤਾ',
    bisOfficeLocator: 'BIS ਦਫ਼ਤਰ ਖੋਜਕ',
    findApplicableStandard: 'ਆਪਣਾ ਲਾਗੂ ਮਿਆਰ ਲੱਭੋ',
    describeProduct: 'ਉਤਪਾਦ ਦਾ ਵਰਣਨ ਕਰੋ',
    searchByIsCode: 'IS ਕੋਡ ਰਾਹੀਂ ਖੋਜੋ',
    uploadDocument: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
    getStandards: 'ਮਿਆਰ ਪ੍ਰਾਪਤ ਕਰੋ',
    verifyBisMark: 'BIS ਮਾਰਕ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    overallProgress: 'ਕੁੱਲ ਤਰੱਕੀ',
    recommendedForYou: 'ਤੁਹਾਡੇ ਲਈ ਸਿਫ਼ਾਰਿਸ਼ ਕੀਤਾ',
    keyRequirements: 'ਮੁੱਖ ਲੋੜਾਂ (ਸੰਖੇਪ)',
    recentActivity: 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ',
    askSugamAi: 'SUGAM-AI ਨੂੰ ਪੁੱਛੋ',
    viewStandard: 'ਮਿਆਰ ਦੇਖੋ',
    whyThisStandard: 'ਇਹ ਮਿਆਰ ਕਿਉਂ?',
    startComplianceJourney: 'ਪਾਲਣਾ ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ',
    viewAll: 'ਸਾਰੇ ਦੇਖੋ',
    searchPlaceholder: 'ਉਤਪਾਦ ਜਾਂ ਮਿਆਰ ਬਾਰੇ ਪੁੱਛੋ...',
    demoDisclaimer: 'ਡੈਮੋ ਡਾਟਾ ਸਿਰਫ਼ ਪ੍ਰਦਰਸ਼ਨ ਲਈ ਹੈ।',
    simplerCompliance: 'ਸਰਲ ਪਾਲਣਾ, ਮਜ਼ਬੂਤ ਭਾਰਤ',
    standardsBuildTrust: 'ਮਿਆਰ ਭਰੋਸਾ ਬਣਾਉਂਦੇ ਹਨ।',
    goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ',
    letsMakeComplianceSimpler: 'ਆਓ ਮਿਲ ਕੇ ਪਾਲਣਾ ਨੂੰ ਆਸਾਨ ਬਣਾਈਏ।',
    activePlans: 'ਸਰਗਰਮ ਯੋਜਨਾਵਾਂ',
    savedStandards: 'ਸੰਭਾਲੇ ਮਿਆਰ',
    verifications: 'ਤਸਦੀਕਾਂ',
    pendingDocuments: 'ਬਕਾਇਆ ਦਸਤਾਵੇਜ਼',
    requiredTests: 'ਲੋੜੀਂਦੇ ਟੈਸਟ',
    documentsRequired: 'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',
    labsNearby: 'ਨੇੜਲੀਆਂ BIS ਲੈਬਾਂ',
    applicableStandards: 'ਲਾਗੂ ਮਿਆਰ',
    signIn: 'ਸਾਈਨ ਇਨ',
    signOut: 'ਸਾਈਨ ਆਉਟ',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ'
  },
  or: {
    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    aiAssistant: 'AI ସହାୟକ',
    productCompliance: 'ଉତ୍ପାଦ ଅନୁପାଳନ',
    standardsSearch: 'ମାନକ ସନ୍ଧାନ',
    bisMarkVerification: 'BIS ମାର୍କ ଯାଞ୍ଚ',
    complianceNavigator: 'ଅନୁପାଳନ ନେଭିଗେଟର୍',
    regulatoryUpdates: 'ନିୟାମକ ଅଦ୍ୟତନ',
    laboratoryFinder: 'ପରୀକ୍ଷାଗାର ସନ୍ଧାନକାରୀ',
    documentsTemplates: 'ଦଲିଲ ଏବଂ ଟେମ୍ପଲେଟ୍',
    complaintsSupport: 'ଅଭିଯୋଗ ଏବଂ ସହାୟତା',
    adminDashboard: 'ଆଡମିନ୍ ଡ୍ୟାସବୋର୍ଡ',
    savedWorkspace: 'ସଂରକ୍ଷିତ କାର୍ଯ୍ୟକ୍ଷେତ୍ର',
    productMatching: 'ଉତ୍ପାଦ ମେଳ',
    claimChecker: 'ଦାବି ଯାଞ୍ଚକାରୀ',
    bisOfficeLocator: 'BIS କାର୍ଯ୍ୟାଳୟ ସନ୍ଧାନ',
    findApplicableStandard: 'ପ୍ରଯୁଜ୍ୟ ମାନକ ଖୋଜନ୍ତୁ',
    describeProduct: 'ଉତ୍ପାଦ ବର୍ଣ୍ଣନା କରନ୍ତୁ',
    searchByIsCode: 'IS କୋଡ୍ ଦ୍ୱାରା ଖୋଜନ୍ତୁ',
    uploadDocument: 'ଦଲିଲ ଅପଲୋଡ୍ କରନ୍ତୁ',
    getStandards: 'ମାନକ ପ୍ରାପ୍ତ କରନ୍ତୁ',
    verifyBisMark: 'BIS ମାର୍କ ଯାଞ୍ଚ କରନ୍ତୁ',
    overallProgress: 'ସାମଗ୍ରିକ ପ୍ରଗତି',
    recommendedForYou: 'ଆପଣଙ୍କ ପାଇଁ ସୁପାରିଶ',
    keyRequirements: 'ମୁଖ୍ୟ ଆବଶ୍ୟକତା (ସାରାଂଶ)',
    recentActivity: 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ',
    askSugamAi: 'SUGAM-AI କୁ ପଚାରନ୍ତୁ',
    viewStandard: 'ମାନକ ଦେଖନ୍ତୁ',
    whyThisStandard: 'ଏହି ମାନକ କାହିଁକି?',
    startComplianceJourney: 'ଅନୁପାଳନ ଯାତ୍ରା ଆରମ୍ଭ କରନ୍ତୁ',
    viewAll: 'ସମସ୍ତ ଦେଖନ୍ତୁ',
    searchPlaceholder: 'ଉତ୍ପାଦ କିମ୍ବା ମାନକ ବିଷୟରେ ପଚାରନ୍ତୁ...',
    demoDisclaimer: 'ଡେମୋ ତଥ୍ୟ କେବଳ ପ୍ରଦର୍ଶନ ପାଇଁ।',
    simplerCompliance: 'ସରଳ ଅନୁପାଳନ, ସଶକ୍ତ ଭାରତ',
    standardsBuildTrust: 'ମାନକ ବିଶ୍ୱାସ ସୃଷ୍ଟି କରେ।',
    goodMorning: 'ଶୁଭ ସକାଳ',
    letsMakeComplianceSimpler: 'ଚାଲନ୍ତୁ ଅନୁପାଳନକୁ ସରଳ କରିବା।',
    activePlans: 'ସକ୍ରିୟ ଯୋଜନା',
    savedStandards: 'ସଂରକ୍ଷିତ ମାନକ',
    verifications: 'ଯାଞ୍ଚ',
    pendingDocuments: 'ବାକି ଥିବା ଦଲିଲ',
    requiredTests: 'ଆବଶ୍ୟକ ପରୀକ୍ଷା',
    documentsRequired: 'ଆବଶ୍ୟକ ଦଲିଲ',
    labsNearby: 'ନିକଟସ୍ଥ BIS ଲ୍ୟାବ୍',
    applicableStandards: 'ପ୍ରଯୁଜ୍ୟ ମାନକ',
    signIn: 'ସାଇନ୍ ଇନ୍',
    signOut: 'ସାଇନ୍ ଆଉଟ୍',
    getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ',
    welcomeBack: 'ସ୍ୱାଗତ'
  },
  as: {
    dashboard: 'ডেশ্ববৰ্ড',
    aiAssistant: 'AI সহায়ক',
    productCompliance: 'সামগ্ৰীৰ অনুপালন',
    standardsSearch: 'মান সন্ধান',
    bisMarkVerification: 'BIS মাৰ্ক পৰীক্ষণ',
    complianceNavigator: 'অনুপালন নেভিগেটৰ',
    regulatoryUpdates: 'নিয়ন্ত্ৰক আপডেট',
    laboratoryFinder: 'পৰীক্ষাগাৰ সন্ধান',
    documentsTemplates: 'নথিপত্ৰ আৰু টেমপ্লেট',
    complaintsSupport: 'অভিযোগ আৰু সমৰ্থন',
    adminDashboard: 'এডমিন ডেশ্ববৰ্ড',
    savedWorkspace: 'সংৰক্ষিত কৰ্মক্ষেত্ৰ',
    productMatching: 'সামগ্ৰী মিলোৱা',
    claimChecker: 'দাবী পৰীক্ষক',
    bisOfficeLocator: 'BIS কাৰ্যালয় সন্ধান',
    findApplicableStandard: 'প্ৰযোজ্য মান সন্ধান কৰক',
    describeProduct: 'সামগ্ৰীৰ বিৱৰণ দিয়ক',
    searchByIsCode: 'IS ক’ডৰে সন্ধান কৰক',
    uploadDocument: 'নথি আপল’ড কৰক',
    getStandards: 'মান প্ৰাপ্ত কৰক',
    verifyBisMark: 'BIS মাৰ্ক পৰীক্ষা কৰক',
    overallProgress: 'সামগ্ৰিক অগ্ৰগতি',
    recommendedForYou: 'আপোনাৰ বাবে পৰামৰ্শ',
    keyRequirements: 'মুখ্য আৱশ্যকতা (সাৰাংশ)',
    recentActivity: 'শেহতীয়া কাৰ্যকলাপ',
    askSugamAi: 'SUGAM-AI ক সোধক',
    viewStandard: 'মান চাওক',
    whyThisStandard: 'এই মান কিয়?',
    startComplianceJourney: 'অনুপালন যাত্ৰা আৰম্ভ কৰক',
    viewAll: 'সকলো চাওক',
    searchPlaceholder: 'সামগ্ৰী বা মানৰ বিষয়ে সোধক...',
    demoDisclaimer: 'ডেমো তথ্য কেৱল প্ৰদৰ্শনৰ বাবে।',
    simplerCompliance: 'সহজ অনুপালন, শক্তিশালী ভাৰত',
    standardsBuildTrust: 'মানে বিশ্বাস গঢ়ে।',
    goodMorning: 'শুভ প্ৰভাত',
    letsMakeComplianceSimpler: 'আহক অনুপালন সহজ কৰি তোলোঁ।',
    activePlans: 'সক্ৰিয় পৰিকল্পনা',
    savedStandards: 'সংৰক্ষিত মান',
    verifications: 'পৰীক্ষণ',
    pendingDocuments: 'বাকী থকা নথিপত্ৰ',
    requiredTests: 'প্ৰয়োজনীয় পৰীক্ষা',
    documentsRequired: 'প্ৰয়োজনীয় নথিপত্ৰ',
    labsNearby: 'ওচৰৰ BIS লেব',
    applicableStandards: 'প্ৰযোজ্য মান',
    signIn: 'ছাইন ইন',
    signOut: 'ছাইন আউট',
    getStarted: 'আৰম্ভ কৰক',
    welcomeBack: 'পুনৰ স্বাগতম'
  }
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (k) => k,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>('en');

  useEffect(() => {
    const saved = localStorage.getItem('sugam_language') as SupportedLanguage;
    if (saved && TRANSLATIONS[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    localStorage.setItem('sugam_language', lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
